In [3]:
import pandas as pd
import numpy as np

pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', 100)

df = pd.read_csv('../data/producao_citros_bruto.csv')

df.head()

,ano,cod_produto,produto,uf,estado,municipio,qtd_produzida_ton,area_colhida_ha,valor_producao_reais
0,2015,41151,Laranja,SP,São Paulo,araraquara,59762,3040.0,30576052.0
1,2016,41151,Laranja,SP,São Paulo,Araraquara,48091,3032.0,42397746.0
2,2017,41151,Laranja,SP,São Paulo,Araraquara,51414,3440.0,51776257.0
3,2018,41151,Laranja,SP,São Paulo,Araraquara,48244,3127.0,33152480.0
4,2019,41151,Laranja,SP,São Paulo,Araraquara,63018,2934.0,39987607.0

In [4]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 3600 entries, 0 to 3599
Data columns (total 9 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   ano                   3600 non-null   int64
 1   cod_produto           3600 non-null   int64
 2   produto               3600 non-null   str
 3   uf                    3600 non-null   str
 4   estado                3600 non-null   str
 5   municipio             3600 non-null   str
 6   qtd_produzida_ton     3484 non-null   str
 7   area_colhida_ha       3438 non-null   float64
 8   valor_producao_reais  3478 non-null   float64
dtypes: float64(2), int64(2), str(5)
memory usage: 253.3 KB

In [5]:
(df == '-').sum()

ano                      0
cod_produto              0
produto                  0
uf                       0
estado                   0
municipio                0
qtd_produzida_ton       97
area_colhida_ha          0
valor_producao_reais     0
dtype: int64

In [6]:
df_clean = df.copy()

Padronizar municípios

In [7]:
df_clean['municipio'] = (
    df_clean['municipio']
    .str.strip()
    .str.title()
)

Substituir "-" por NaN

In [8]:
df_clean = df_clean.replace('-', np.nan)

Converter colunas numéricas

In [9]:
colunas_numericas = [
    'qtd_produzida_ton',
    'area_colhida_ha',
    'valor_producao_reais'
]

for col in colunas_numericas:
    df_clean[col] = pd.to_numeric(df_clean[col], errors='coerce')

Verificar tipos

In [10]:
df_clean.info()

<class 'pandas.DataFrame'>
RangeIndex: 3600 entries, 0 to 3599
Data columns (total 9 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   ano                   3600 non-null   int64
 1   cod_produto           3600 non-null   int64
 2   produto               3600 non-null   str
 3   uf                    3600 non-null   str
 4   estado                3600 non-null   str
 5   municipio             3600 non-null   str
 6   qtd_produzida_ton     3387 non-null   float64
 7   area_colhida_ha       3438 non-null   float64
 8   valor_producao_reais  3478 non-null   float64
dtypes: float64(3), int64(2), str(4)
memory usage: 253.3 KB

Verificar áreas inválidas

In [11]:
registros_invalidos = df_clean[
    (df_clean['area_colhida_ha'] <= 0) |
    (df_clean['qtd_produzida_ton'] <= 0)
]

registros_invalidos.shape

(0, 9)

Filtrar apenas registros válidos

In [12]:
df_clean = df_clean[
    (df_clean['area_colhida_ha'] > 0) &
    (df_clean['qtd_produzida_ton'] > 0)
]

Criar produtividade

In [13]:
df_clean['produtividade_ton_ha'] = (
    df_clean['qtd_produzida_ton'] /
    df_clean['area_colhida_ha']
)

Conferência final

In [14]:
df_clean.describe()

,ano,cod_produto,qtd_produzida_ton,area_colhida_ha,valor_producao_reais,produtividade_ton_ha
count,3234.000000,3234.000000,3234.000000,3234.000000,3.124000e+03,3234.000000
mean,2019.000309,41160.573593,6781.592455,669.541744,6.720775e+06,10.452548
std,2.582688,9.551349,14181.420187,886.756646,1.252624e+07,10.017067
min,2015.000000,41151.000000,105.000000,45.000000,8.035900e+04,0.392771
25%,2017.000000,41155.000000,1154.000000,191.000000,1.303647e+06,3.895908
50%,2019.000000,41160.000000,2029.500000,364.000000,2.666222e+06,7.305758
75%,2021.000000,41176.000000,7293.750000,789.750000,7.511659e+06,13.939570
max,2023.000000,41176.000000,134485.000000,7413.000000,1.371068e+08,85.108911